#186: Clean up OSGi manifest headers (without any impact in JavaEE/Ja…
eclipse-ee4j/jta-api pull request #187
Opened 2021-02-11 11:15 UTC by grgrzybek

…kartaEE aspects)

2021-02-11 11:41 UTC, tomjenkinson commented on api/pom.xml
> +        <relativePath />
Is this required?

2021-02-11 11:42 UTC, tomjenkinson commented on api/pom.xml
> -                        <Import-Package>javax.interceptor.*;version="[1.2,1.2.98)",*</Import-Package>
I wonder what the 1.2.98 was about? I don't think that restriction is present any longer in your version, can you speak to the impact please?

2021-02-11 11:43 UTC, tomjenkinson commented
ok to test

2021-02-11 12:00 UTC, grgrzybek commented on api/pom.xml
> +        <relativePath />
It doesn't change anything when invoking `mvn clean install` at top level, but when running `mvn clean install -f api`, it prevents this warning:
```
[WARNING] Some problems were encountered while building the effective model for jakarta.transaction:jakarta.transaction-api:jar:1.3.4-SNAPSHOT
[WARNING] 'parent.relativePath' of POM jakarta.transaction:jakarta.transaction-api:1.3.4-SNAPSHOT (/data/sources/github.com/eclipse-ee4j/jta-api/api/pom.xml) points at jakarta.transaction:jakarta.transaction-parent instead of org.eclipse.ee4j:project, please verify your project structure @ line 22, column 13
```

And indeed - default value for `<relativePath>` is `../pom.xml`, which here is `jakarta.transaction:jakarta.transaction-api` and not `org.eclipse.ee4j:project`

2021-02-11 12:02 UTC, grgrzybek commented on api/pom.xml
> -                        <Import-Package>javax.interceptor.*;version="[1.2,1.2.98)",*</Import-Package>
I tracked down https://github.com/javaee/javax.transaction/blame/master/pom.xml#L177 change, but I have no idea about the reasons behind it...

2021-02-11 12:05 UTC, grgrzybek commented
btw, I've amended the PR with sign-off and the build failed due to wrong (default) `<relativePath>` in spec subproject (see https://ci.eclipse.org/jta/job/eclipse-ee4j_jta-api-pulls/242/console):
```
[FATAL] Non-resolvable parent POM for jakarta.transaction:transactions-spec:1.3: Could not find artifact jakarta.transaction:jakarta.transaction-parent:pom:1.3.3-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 20, column 13
```

2021-02-11 12:17 UTC, grgrzybek commented
Build failed because of some problems with ... Glassfish build (probably some post JTA API build related to TCK?)
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project tiger-types: Fatal error compiling: invalid target release: 11 -> [Help 1]
```

2021-02-11 12:32 UTC, tomjenkinson commented
It looks like something to do with JDK11 I think related to Glassfish

2021-03-12 15:48 UTC, tomjenkinson commented
retest this please

2021-03-16 11:32 UTC, tomjenkinson commented on api/pom.xml
> +                            javax.interceptor.*;version="1.2",
@grgrzybek I am wondering if this should be `javax.interceptor.*;version="[1.2,1.2.98)"` and if not why not?

2021-03-16 11:39 UTC, tomjenkinson commented on api/pom.xml
> +                            javax.enterprise.context;version=!,
Please can you explain for me what the "!" means?

2021-03-16 11:40 UTC, tomjenkinson commented on api/pom.xml
> +        <relativePath />
Please can it be split to a different commit?

2021-03-16 11:57 UTC, grgrzybek commented on api/pom.xml
> +                            javax.interceptor.*;version="1.2",
1.2.98 comes from https://github.com/javaee/javax.transaction/commit/341344a51baea82a848d6787ba3fea89f2ce2f8d and I can't find any justification for it.
Knowing the resolution process of OSGi runtimes (Felix, Equinox), it is safe to import this package at version 1.2 without upper boundary.

2021-03-16 11:57 UTC, tomjenkinson commented
retest this please

2021-03-16 11:58 UTC, tomjenkinson commented
Seems like master of glassfish requires JDK 11. I found https://github.com/eclipse-ee4j/glassfish/tree/6.0.0-BRANCH which hopefully (a guess though) would be the maintenance branch for Jakarta EE 9

2021-03-16 11:59 UTC, tomjenkinson commented
@grgrzybek please can you raise the PR against `master` branch? If it's merged then we could look at backports

2021-03-16 12:00 UTC, grgrzybek commented on api/pom.xml
> +                            javax.enterprise.context;version=!,
`!` means that maven-bundle-plugin should not add _any_ import package version range for this imported package.
The reason is that jakarta.transaction-api uses only annotations which should not be removed from CDI in any foreseeable future.
jakarta.transaction-api works safely with both CDI 1.2 and 2 and it'd be unnatural to explicitly constraint the version range to `[1.2,3)` when CDI 3 is ready (I think so).

2021-03-16 12:06 UTC, grgrzybek commented
PR against master: #188

2021-03-16 12:53 UTC, tomjenkinson commented on api/pom.xml
> +        <relativePath />
I think when this is done (and we see CI pass again) it's OK to merge

2021-03-16 12:56 UTC, tomjenkinson requested changes

2021-03-16 12:56 UTC, tomjenkinson commented on spec/pom.xml
> +        <version>1.3.4-SNAPSHOT</version>
Actually, please can you put it in a different commit and use the wording "Prepare next development cycle for 1.3.4-SNAPSHOT" (like https://github.com/eclipse-ee4j/jta-api/commit/94598a42e995829afe1f64bffb305da731322934)

2021-03-16 14:49 UTC, grgrzybek commented on spec/pom.xml
> +        <version>1.3.4-SNAPSHOT</version>
should https://github.com/eclipse-ee4j/jta-api/pull/188 be built first? Then it could be backported from `master`. I don't think `RELEASE-1.3.3` branch is a good branch to prepare for 1.3.4 release. There are multiple similar branches:
```
15:46 $ git ls-remote origin
1ca0e56d0860bc92744185fe26e1c2cfb4b4f5a5	HEAD
82b1aebf2b27bdc576851faf7aad2d13b488ad60	refs/heads/RELEASE-1.3.1
10174ac9fb2db4bd177b6dbd0d2b4ee23aede1a7	refs/heads/RELEASE-1.3.2
94598a42e995829afe1f64bffb305da731322934	refs/heads/RELEASE-1.3.3
178cd37b687c9bba22448c407a1bfb1457fc6e6b	refs/heads/RELEASE-2.0.0-RC1
3a20f83811d22854266e7eeb1323ea3dce0a9577	refs/heads/RELEASE-2.0.0-RC2-staging
622306e5220472c98f7ce1ef1e8d8dc2ce9b52f5	refs/heads/RELEASE-2.0.0-RC3-staging
98a654c8c0ba4e0c3ac14950275add1c8ed9ff42	refs/heads/RELEASE-2.0.0-staging
```

2021-03-16 15:15 UTC, tomjenkinson commented on spec/pom.xml
> +        <version>1.3.4-SNAPSHOT</version>
Good point, I do think `RELEASE-1.3.3` is the right branch if we want to have a version for Jakarta EE 8 but I think I will backport it myself from master and close this PR. Thanks for the contribution!

2021-03-16 15:31 UTC, tomjenkinson commented
I will close this PR, the follow-up is here: https://github.com/eclipse-ee4j/jta-api/pull/189

2021-03-16 15:31 UTC, closed without merging