Changes needed to build without errors/warnings using JDK11
eclipse-ee4j/jta-api pull request #199
Opened 2022-01-25 03:38 UTC by starksm64

These are the changes I needed to do in order to build the project using JDK11. This still is producing JDK8 source/binary artifacts.

2022-01-25 06:58 UTC, pzygielo commented on spec/pom.xml
> +                                    <message>You need JDK11 or lower</message>
`lower` doesn't sound right here.

2022-01-25 07:28 UTC, starksm64 commented
Note I added the module-info and updated cdi, interceptors to service releases that include a proper module-info. 

We should try to get an RC release out based on this.

2022-01-25 07:30 UTC, starksm64 commented on spec/pom.xml
> +                                    <message>You need JDK11 or lower</message>
Right, I have corrected that

2022-01-26 16:25 UTC, tomjenkinson approved these changes

2022-01-26 16:29 UTC, tomjenkinson requested changes

2022-01-26 16:29 UTC, tomjenkinson commented on spec/pom.xml
> +                                    <version>[11.0,17.0)</version>
Is it correct to list `17.0` here?

2022-01-26 16:32 UTC, starksm64 commented on spec/pom.xml
> +                                    <version>[11.0,17.0)</version>
That is the upper bound we are targeting in EE10, but really it does not matter. It could be fixed to just 11. I'll leave it up to you.

2022-01-26 17:13 UTC, starksm64 commented on spec/pom.xml
> +                                    <version>[11.0,17.0)</version>
It is captured in this platform issue: https://github.com/eclipse-ee4j/jakartaee-platform/issues/331
We will come up with a more formal statement in the platform spec requirements in the future.

2022-01-26 18:25 UTC, pzygielo commented on spec/pom.xml
> +                                    <version>[11.0,17.0)</version>
Why 17+ can't be used to build this project? (`)` -> `17.0 not included` in the range)
17 is already released LTS if I'm not mistaken.
Why limit the JDK usable for building from the top at all, while `--release` flag is used?

2022-01-27 07:59 UTC, pzygielo commented on spec/pom.xml
> +                                    <version>[11.0,17.0)</version>
Only now I noticed this is change in `spec` project, and nothing is enforced in `api`. And `spec` is not included in top level project anyway.

2022-01-27 15:26 UTC, tomjenkinson commented
retest this please

2022-01-27 15:28 UTC, tomjenkinson commented on spec/pom.xml
> +                                    <version>[11.0,17.0)</version>
I guess it is historic to be located in this part of the pom but upon deeper reflection I think the upper bound should be removed (and if it is not the message below would not be accurate anyway. Scott, please can you remove the upper bound?

2022-01-27 15:30 UTC, tomjenkinson commented
I am trying to retest with https://download.eclipse.org/jakartaee/transactions/2.0/jakarta-transactions-tck-2.0.1.zip

2022-01-28 03:40 UTC, starksm64 commented on spec/pom.xml
> +                                    <version>[11.0,17.0)</version>
Change to simply 11

2022-01-31 17:16 UTC, tomjenkinson commented
retest this please

2022-01-31 17:17 UTC, tomjenkinson commented
I am trying to retest with 2.0.2 of the TCK following the comment from Alwin (https://github.com/eclipse-ee4j/jakartaee-tck/issues/812#issuecomment-1025712502)

2022-02-01 16:45 UTC, tomjenkinson commented
retest this please

2022-02-01 17:05 UTC, tomjenkinson commented
retest this please

2022-02-01 17:38 UTC, tomjenkinson commented
retest this please

2022-02-02 14:09 UTC, tomjenkinson approved these changes
I will mention that the current JDK11 build of `master` works without these changes:
https://ci.eclipse.org/jta/job/eclipse-ee4j_jta-api-openjdk-jdk11-latest/22/

Thanks for the contribution, I am approving.

2022-02-02 14:09 UTC, merged