Create tck_challenge.md
eclipse-ee4j/jta-api pull request #217
Opened 2024-09-19 16:22 UTC by Emily-Jiang

2024-09-23 10:39 UTC, tomjenkinson commented
@Emily-Jiang it looks good to me and I though I could likely be able to review it without the following request, in case it's available I would ask if this format is a template/document from someplace we can reference as a motivating factor for the introduction of, please?

2024-09-23 16:24 UTC, Emily-Jiang commented
> @Emily-Jiang it looks good to me and I though I could likely be able to review it without the following request, in case it's available I would ask if this format is a template/document from someplace we can reference as a motivating factor for the introduction of, please?

Not sure whether you can view this. [This](https://github.com/jakartaee/specification-committee/issues/58) request is from Jakarta EE specification committee.
You can find another example of this tck challenge [here](https://github.com/jakartaee/platform/blob/main/.github/ISSUE_TEMPLATE/tck_challenge.md).

2024-09-24 15:50 UTC, edburns commented on .github/ISSUE_TEMPLATE/tck_challenge.md
> +ee.jakarta.tck.faces.test.javaee7.multiFieldValidation.Spec1IT#testFailingPreconditionsNotAfterAllInputComponents
Use a fake package name.

2024-09-24 15:50 UTC, edburns commented on .github/ISSUE_TEMPLATE/tck_challenge.md
> +Specify the version of the TCK, e.g. Jakarta Faces 4.0.x
Use a fake spec name. That way you can get rid of the `e.g.`

2024-09-24 15:51 UTC, edburns requested changes
Some small changes requested.

2024-09-24 16:02 UTC, Emily-Jiang commented on .github/ISSUE_TEMPLATE/tck_challenge.md
> +ee.jakarta.tck.faces.test.javaee7.multiFieldValidation.Spec1IT#testFailingPreconditionsNotAfterAllInputComponents
```suggestion
ee.jakarta.tck.wombat.MyTest#testSomething
```

2024-09-24 16:03 UTC, Emily-Jiang commented on .github/ISSUE_TEMPLATE/tck_challenge.md
> +Specify the version of the TCK, e.g. Jakarta Faces 4.0.x
```suggestion
Specify the version of the TCK, e.g. Jakarta Transactions 2.x
```

2024-09-24 16:54 UTC, tomjenkinson commented on .github/ISSUE_TEMPLATE/tck_challenge.md
> +Specify the version of the TCK, e.g. Jakarta Transactions 2.x
I _guess_ this could be `Jakarta Wombat 2.x` given line 12.

But even if you agree with the consistency, before making that change I am wondering if we would not prefer to have transactions in here rather than wombat to help people understand how to raise the challenge on this project [rather than generically describing "wombat"]?

What do you think?

2024-10-01 15:14 UTC, Emily-Jiang commented on .github/ISSUE_TEMPLATE/tck_challenge.md
> +Specify the version of the TCK, e.g. Jakarta Transactions 2.x
```suggestion
Specify the version of the TCK, e.g. Jakarta Wombat x.x
```

2024-10-01 15:15 UTC, Emily-Jiang commented on .github/ISSUE_TEMPLATE/tck_challenge.md
> +
I don't quite understand what you meant. It is not my aim to prompt people to review the process. If you want to achieve that, please feel free to propose a PR.

2024-10-01 15:16 UTC, Emily-Jiang commented on .github/ISSUE_TEMPLATE/tck_challenge.md
> +
If someone came here to raise a challenge, they might have visited the tck process.

2024-10-01 15:34 UTC, tomjenkinson commented on .github/ISSUE_TEMPLATE/tck_challenge.md
> +
It is important that the challenge is filed by an appropriate person: https://jakarta.ee/committees/specification/tckprocess/#_who_can_file_a_challenge - is there someway that during raising the challenge information can be provided so it can be verified an implementor is raising the issue?

I think you should also provide space for the other parts of the requirements when filing a challenge:
https://jakarta.ee/committees/specification/tckprocess/#_filing_a_challenge. I think most of this fits nicely in your format but perhaps the following should have their own sections?:
* The relevant specification version and section number(s)
* The implementation being tested, including name and company (maybe this is the first part of this comment?)

2024-10-01 15:37 UTC, tomjenkinson commented
Do you know how GitHub behaves if only one one template exists in the repo? In other words, do you know if someone would be able to raise an issue on this project but not using the new template (after this pull request is merged)?

2026-02-18 17:27 UTC, merged